### ISSUE TITLE
bug in dataset

### ISSUE THREAD

**Issue by wanggaa** [microsoft/two-for-one-diffusion#1]
![image](https://github.com/microsoft/two-for-one-diffusion/assets/7566291/f612f527-2fae-48aa-ba57-abcd8300707a)
如上图，你使用了subset.dataset来构建一个新CGDataset

![image](https://github.com/microsoft/two-for-one-diffusion/assets/7566291/d7d148f2-98fd-4ddd-a1e5-0fa11e4b79b4)
但是实际上subset.dataset是指初始化这个subset时输入的数据，表示整个数据库

这表示所有的subset都是使用全部的数据构建的，包括训练、评估、测试数据集，所有的对应过程都在同一个数据集上，得到的三个数据集长度也都是同样的大小。

**Comment by vgsatorras** [comment]
Hi,

Thank you for highlighting this issue. I'd like to clarify that this codebase is specifically designed for sampling and evaluation with pretrained models, as detailed in  [this section of the Readme](https://github.com/microsoft/two-for-one-diffusion?tab=readme-ov-file#training-the-diffusion-model). Consequently, certain parts of the code used for training and data loading have been omitted/modified and left as a placeholder, such as the code contained in [dataset_utils_empty.py](https://github.com/microsoft/two-for-one-diffusion/blob/main/datasets/dataset_utils_empty.py) that you are referencing, which dataset is an empty array `dataset = torch.zeros(1)`.

However, you are correct that this function, when provided with the correct dataset would return the whole dataset instead of the correct splits. The original `get_subset` function used in our training codebase handles data splitting correctly. To rectify this and provide clarity for those looking to adapt the two-for-one code, I have updated the function to reflect the original implementation used in our training codebase:

![image](https://github.com/microsoft/two-for-one-diffusion/assets/6526644/711dadf3-3a31-4a60-b07c-ee9f1c1f70b0)
